### ISSUE TITLE
Performances, Accessibility, and Browser Testing

### ISSUE THREAD

**Issue by JessJodoin** [JessJodoin/animal-rescue-website#1]
Hi @charlie-quinn

Here is a link to my google spread that you can edit.

https://docs.google.com/spreadsheets/d/1nvGivSdRicnPDeD21wec0gx-Mv-e4nEGtyJmmclSrhs/edit?usp=sharing

Thanks,
Jess

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded.`

⚠️`Reminder: please close this issue once it has been resolved.`
