### ISSUE TITLE
Request for Grade

### ISSUE THREAD

**Issue by JessJodoin** [JessJodoin/animal-rescue-website#2]
Hi @charlie-quinn

For this assignment, I think I deserve an A- because I applied many of the material we learned over this semester. In my website, I used techniques we learned to make websites quick and accessible, I used the retina images and smushed all images, I made favicons and put them through their respective program to make them into one file, and I cut out all the unnecessary code from all my index and css files.

During this assignment I did have some struggles, particularly with making my navigation on small screens a toggle navigation. I had issues because, for the sake accessibility, a toggle navigation has difficulty with focus states making it not very accessible. I tried to make it work but ultimately changed my navigation to a standard navigation so that it would be accessible for all users. I also struggled with Markbot expecting the embed classes on the form page. I didn't want any images on the adopt page so I made a hidden image with the embed classes (I know.. that's dumb but I had to appease Markbot).

Overall, I am very happy with how my website has turned out and I think it shows that I can apply everything I’ve learned in Wed Dev 3.

Thanks for the great semester!
Jess Jodoin

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`
